name: gdp-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5
  - numpy>=1.21
  - matplotlib>=3.5
  - seaborn>=0.11
  - openpyxl>=3.0
  - jupyter>=1.0
  - ipykernel>=6.0
  - pip
  - pip:
    - no-requirements